server:
  port: 9091
spring:
  datasource:
    username: root
    password: match.123
    url: jdbc:mysql://localhost:3306/movic?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.heaven.entity